# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('description', models.TextField(default='No description yet.')),
                ('price', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='CPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Character Photo')),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waifusite.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField(default=1990)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waifusite.Origin'),
        ),
    ]
