# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waifusite', '0002_auto_20170505_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cphoto',
            old_name='product',
            new_name='character',
        ),
    ]
