# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waifusite', '0003_auto_20170508_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='Affordable WAIFU at your doorstep', max_length=50),
        ),
    ]
